name: Publish Docker Container

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - master
  pull_request:

env:
  IMAGE_NAME: vlmcsd

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

  push-image:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'schedule'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file Dockerfile --tag image
      - name: Log into registry
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=${{secrets.DOCKER_USERNAME}}/$IMAGE_NAME
          VERSION=`curl https://github.com/Wind4/vlmcsd/tags | grep '<a href="/Wind4/vlmcsd/releases/tag/' | cut -d '"' -f 2 | cut -d '/' -f 6 | head -1`
          CHECK_VERSION=`curl -L https://mogeko.github.io/docker-vlmcsd/index.json | grep version | cut -d '"' -f 8`
          if [ "$VERSION" != "$CHECK_VERSION" ]; then
            echo IMAGE_ID=$IMAGE_ID
            echo VERSION=$VERSION
            docker tag image $IMAGE_ID:$VERSION
            docker push $IMAGE_ID:$VERSION
          fi
      - name: Update Version Info
        run: echo "{\"date\":\"`date "+%FT%T%:z"`\",\"version\":\"$VERSION\"}" > index.json
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: index.json
      - name: Departure update
        run: |
          echo '{"soure_type": "Branch", "source_name": "master"}' > update.json
          curl -H 'Content-Type: application/json' --data @update.json -X POST ${{secrets.BUILD_WEBHOOK}}

  update-version-info:
    needs: push-image
    runs-on: ubuntu-latest
    container:
      image: alpine/git
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: version
    - name: Setup git
      run: |
        git config --global user.name 'Mogeko'
        git config --global user.email 'zhengjunyi@live.com'
    - name: Deploy to GitHub
      run: |
        git init && git add .
        for try in $(seq 10); do
          git commit -m "Build By GitHub Actions on $(date "+%Y-%m-%d %T")"
          if git push -f "https://${{ secrets.BUILD_TOKEN }}@github.com/Mogeko/docker-vlmcsd" master:gh-pages; then
            exit 0
          else
            sleep $(shuf -i 3-10 -n 1)
          fi
        done
        exit 1
